import requests

def check_username(username):
    social_sites = [
        "https://www.pornhub.com/users/{username}/",
        "https://www.instagram.com/{username}/",
        "https://www.twitter.com/{username}/",
        "https://www.facebook.com/{username}/",
        "https://www.pinterest.com/{username}/",
        "https://www.linkedin.com/in/{username}/",
        "https://www.reddit.com/user/{username}/",
        "https://www.youtube.com/{username}/",
        "https://www.tumblr.com/blog/{username}/",
        "https://soundcloud.com/{username}/",
        "https://vimeo.com/{username}/",
        "https://www.flickr.com/people/{username}/",
        "https://www.github.com/{username}/",
        "https://www.medium.com/@{username}/",
        "https://www.quora.com/profile/{username}/",
        "https://www.deviantart.com/{username}/",
        "https://about.me/{username}/",
        "https://www.behance.net/{username}/",
        "https://www.goodreads.com/{username}/",
        "https://www.wattpad.com/user/{username}/",
        "https://www.snapchat.com/add/{username}/",
        "https://www.producthunt.com/@{username}/",
        "https://www.dribbble.com/{username}/",
        "https://www.last.fm/user/{username}/",
        "https://www.mix.com/{username}/",
        "https://www.houzz.com/user/{username}/",
        "https://www.hackerone.com/{username}/",
        "https://www.spotify.com/{username}/",
        "https://www.okcupid.com/profile/{username}/",
        "https://www.steamcommunity.com/id/{username}/",
        "https://www.bandcamp.com/{username}/",
        "https://www.slideshare.net/{username}/",
        "https://www.blogger.com/profile/{username}/",
        "https://www.academia.edu/{username}/",
        "https://www.fiverr.com/{username}/",
        "https://www.twitch.tv/{username}/",
        "https://www.patreon.com/{username}/",
        "https://www.mixcloud.com/{username}/",
        "https://www.flipboard.com/@{username}/",
        "https://www.couchsurfing.com/people/{username}/",
        "https://www.tripadvisor.com/members/{username}/",
        "https://www.trip.com/members/{username}/",
        "https://www.cnet.com/profiles/{username}/",
        "https://www.anime-planet.com/users/{username}/",
        "https://www.alltrails.com/members/{username}/",
        "https://www.photobucket.com/user/{username}/",
        "https://www.gaiaonline.com/profiles/{username}/",
        "https://www.imgur.com/user/{username}/",
        "https://www.patreon.com/{username}/",
        "https://www.meetup.com/members/{username}/",
        "https://www.fandom.com/u/{username}/",
        "https://www.gamespot.com/profile/{username}/",
        "https://www.ask.fm/{username}/",
        "https://www.chefsfeed.com/chefs/{username}/",
        "https://www.gamesradar.com/user/{username}/",
        "https://www.cookinglight.com/user/{username}/",
        "https://www.myspace.com/{username}/",
        "https://www.instructables.com/member/{username}/",
        "https://www.codepen.io/{username}/",
        "https://www.codecademy.com/profiles/{username}/",
        "https://www.ted.com/profiles/{username}/",
        "https://www.hackerrank.com/{username}/",
        "https://www.joindiaspora.com/people/{username}/",
        "https://www.coroflot.com/{username}/",
        "https://www.fotolog.com/{username}/",
        "https://www.livejournal.com/profile/{username}/",
        "https://www.wikihow.com/User:{username}/",
        "https://www.minds.com/{username}/",
        "https://www.angel.co/{username}/",
        "https://www.pexels.com/@{username}/",
        "https://www.500px.com/{username}/",
        "https://www.fontspace.com/profile/{username}/",
        "https://www.themeforest.net/user/{username}/",
        "https://www.kickstarter.com/profile/{username}/",
        "https://www.drupal.org/u/{username}/",
        "https://www.thingiverse.com/{username}/",
        "https://www.tinkercad.com/users/{username}/",
        "https://www.gettyimages.com/photos/{username}/",
        "https://www.genius.com/{username}/",
        "https://www.tiktok.com/@{username}/",
        "https://www.periscope.tv/{username}/",
        "https://www.storenvy.com/{username}/",
        "https://www.etsy.com/shop/{username}/",
        "https://www.ioby.org/users/{username}/",
        "https://www.yelp.com/user_details?userid={username}/",
        "https://www.acast.com/{username}/",
        "https://www.podbean.com/{username}/",
        "https://www.spreaker.com/user/{username}/",
        "https://www.blubrry.com/{username}/",
        "https://www.weheartit.com/{username}/",
        "https://www.kickstarter.com/profile/{username}/",
        "https://www.tildacdn.com/{username}/",
        "https://www.discogs.com/user/{username}/",
        "https://www.modelmayhem.com/{username}/",
        "https://www.carbonmade.com/{username}/",
        "https://www.cargocollective.com/{username}/",
        "https://www.voyce.me/users/{username}/",
        "https://www.pixabay.com/users/{username}/",
        "https://www.pond5.com/artist/{username}/",
        "https://www.adobe.com/express/pages/{username}/",
        "https://www.notion.so/{username}/",
        "https://www.jumpshare.com/v/{username}/",
        "https://www.artstation.com/{username}/",
        "https://www.hey.com/{username}/",
        "https://www.are.na/{username}/",
        "https://www.plurk.com/{username}/",
        "https://www.f6s.com/{username}/",
        "https://www.weibo.com/{username}/",
        "https://www.yummly.com/user/{username}/",
        "https://www.hotmart.com/{username}/",
        "https://www.eyeka.com/u/{username}/",
        "https://www.mixbook.com/{username}/",
        "https://www.quora.com/profile/{username}/",
        "https://www.chess.com/member/{username}/",
        "https://www.muckrack.com/{username}/",
        "https://www.kongregate.com/accounts/{username}/",
        "https://www.spelltable.wizards.com/users/{username}/",
        "https://www.yelp.com/user_details?userid={username}/",
    ]

    for site in social_sites:
        try:
            response = requests.get(site.format(username=username))
            if response.status_code == 200:
                print(f"The Person Is On : {site.format(username=username)}")
            else:
                print(f"The Person Is Not Regissterd Or Find On The : {site.format(username=username)}")
        except requests.RequestException as e:
            print(f"Error checking {site.format(username=username)}: {e}")

# استفاده از تابع
username_to_check = input("Enter a username to check: ")
check_username(username_to_check)
